version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-crm-app
    container_name: crm-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
    - "5173:5173"
    
    volumes:
      - ./app/:/var/www/html
    
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: crm-nginx
    ports:
      - "8000:80"
    volumes:
      - ./app/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_pass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: